### ISSUE TITLE
Source map URL should be resolved relative to resource

### ISSUE THREAD

**Issue by jscheid** [stacktracejs/stacktrace-gps#10]
Hi,

Suppose my `location.href` is `http://localhost/foo/` and I'm loading `/bundle.js` which references a source map `bundle.js.map` using just this relative path (e.g. just the filename).

stacktrace-gps currently resolves the sourcemap URL relative to the current page (implicitly, from what I can see) and will therefore try to load `http://localhost/foo/bundle.js.map`. However, the URL should be resolved relative to the resource, i.e. to `http://localhost/bundle.js.map`.

**Comment by eriwen** [comment]
Fixed by 20042831f6a3f8aed19abd9e98bdc1e42b6ef82f :star2:
