### ISSUE TITLE
Include Source-Maps dependency 

### ISSUE THREAD

**Issue by niemyjski** [stacktracejs/stacktrace-gps#15]
Would it be possible to include the source maps dependency in the dist folder. I've had issues building it: https://github.com/mozilla/source-map/issues/179 and it's not even included in their build (I can't just pull it in). This would be a huge help..

Also, I was wondering what all that library supports, it looks like it does everything but at the expense of being 25kb minified (which is pretty big to be sending down over the wire).

**Comment by eriwen** [comment]
Yes, definitely will do this.

I tried for awhile to split the source map consumer out with no success. I'd love it if someone else could succeed where I failed there.

**Comment by niemyjski** [comment]
I'm currently blocked on this as I can't get that dependency to work (fails every time to resolve). I'd be willing to help pair on it with you. From the looks of it other libraries just to very basic source maps (TraceKit). I wonder if we could take that.

**Comment by niemyjski** [comment]
I've been trying all luck to make changes to source-maps to get them to resolve correctly and am not having any luck. It kind of seems that mozilla has no intention of doing anything outside of how/what they use it for.

**Comment by niemyjski** [comment]
I still haven't had any luck. @eriwen have you?

**Comment by eriwen** [comment]
Switched to `gulp` and `dist/stacktrace.min.js` now includes all dependencies (without polyfills). Fixed by  20042831f6a3f8aed19abd9e98bdc1e42b6ef82f
