### ISSUE TITLE
"sourceMappingURL not found" when trying to pinpoint a stackframe from js bundled by ASP.NET

### ISSUE THREAD

**Issue by westsajd** [stacktracejs/stacktrace-gps#21]
Hi,
i have a js bundle minified by [ASP.NET Web Optimization](https://aspnetoptimization.codeplex.com/) and source maps generated by [AspNetBundling](https://github.com/benmccallum/AspNetBundling). Mapped stack trace (after exception thrown) is working fine in Chrome but when i try to pinpoint a stackframe it gives me "sourceMappingURL not found" error.

Code for getting a stack:
```javascript
var callback = function (stackframes) {
                var gps = new StackTraceGPS();

                _.each(stackframes, function (stackframe) {
                    console.info("Unpinned:");
                    console.log(stackframe);

                    gps.pinpoint(stackframe)
                        .then(function (pinned) {
                            console.log(pinned);
                        })
                        .catch(function (err) {
                            console.error(err);
                        });
                });
            };

            var errback = function (err) {
                console.log(err.message);
            };

            StackTrace.get().then(callback).catch(errback);
```

Single stackframe looks like this:
```
t {
fileName: "http://suzi/bundles/suzi?v=hf2njH4HOG6YMOecHaDuOrRx2tvdViVb8O5gT54rOzg1",
lineNumber: 1, 
columnNumber: 211552, 
source: "    at http://suzi/bundles/suzi?v=hf2njH4HOG6YMOecHaDuOrRx2tvdViVb8O5gT54rOzg1:1:211552"}
```

Bundle is accessible and has proper sourceMappingURL attached: 
![capture](https://cloud.githubusercontent.com/assets/3727799/10709451/7a2f29f6-7a2f-11e5-899f-13c192989417.PNG)

Also XHR returns with status 200:
![capture3](https://cloud.githubusercontent.com/assets/3727799/10709481/7f21b234-7a30-11e5-965f-47ae2743cc56.PNG)

I end up with:
![capture2](https://cloud.githubusercontent.com/assets/3727799/10709473/24fa37ae-7a30-11e5-9192-6eb7fc86a36a.PNG)

**Comment by oliversalzburg** [comment]
Weird, I don't see why [the regular expression](https://github.com/stacktracejs/stacktrace-gps/blob/master/stacktrace-gps.js#L99) doesn't match.

**Comment by eriwen** [comment]
Is that a space between # and sourceMappingUrl at the end of the source file?




That would definitely be a problem.

**Comment by westsajd** [comment]
@eriwen I was using release 1.0.1.

I have moved to Gulp instead of ASP.NET Web Optimization and everything works fine now so i suppose i can close this :)

**Comment by andreykl** [comment]
Hello guys,

please, open this issue again because I still have this problem.

It happens because you have different files in dist and in source.
In your sources you have correct regular expression with **\s*** at the end (please, take a look [stacktrace-gps.js#L99](https://github.com/stacktracejs/stacktrace-gps/blob/master/stacktrace-gps.js#L99)). But it looks like in your dist you have an old version of file, where regular expression is without **\s*** (please, take a look [dist/stacktrace-gps.js#L99](https://github.com/stacktracejs/stacktrace-gps/blob/master/dist/stacktrace-gps.js#L99))

Thank you

**Comment by oliversalzburg** [comment]
@andreykl Thanks a lot for the detailed description! I've rebuilt the `dist` files and published a new version as 2.3.2. Please let me know if that resolves the issue.

**Comment by andreykl** [comment]
it works now

thank you very much for the fast fix!

**Comment by Oranji-Aka** [comment]
Hello all,

i still have the problem with the ASP NET Web optimization.

Context of my bundling
a Bundle class with all the business script(angular, jquery, etc)
a ScriptWithSourceMapBundle with all my front-end js.

If i put the stacktrace in the ScriptWithSourceMapBundle Chrome and FireFox works fine but Edge and EI is not too thrill about it.
![sourcemap](https://cloud.githubusercontent.com/assets/8930020/14431356/47ef1bca-ffd3-11e5-815f-527646c1e61e.PNG)

then if i put the stracktrace in the Bundle object Edge and IE are fine but Chrome and Firefox are not happy campers. Where it reserve the error, 404 on get Stacktrace.min.js

I'm a bit clueless on how to resolve this. May be it's a bug from the Web Optimization.
