### ISSUE TITLE
stacktrace-js bower dependencies missing

### ISSUE THREAD

**Issue by elesueur** [stacktracejs/stacktrace-gps#22]
stacktrace-js depends on stack-generator, stacktrace-gps and error-stack-parser, but they are not encoded in the dependencies, so bower does not download them when you add a dependency on stacktrace-js.

Is there a reason why the dependencies are left out?

**Comment by oliversalzburg** [comment]
The [`bower.json`](https://github.com/stacktracejs/stacktrace.js/blob/master/bower.json) should be fine. What version are you using?

**Comment by elesueur** [comment]
I am using 1.0.0...

**Comment by elesueur** [comment]
OK, I see 1.0.1 has the correct dependencies.
