### ISSUE TITLE
SourceMap case

### ISSUE THREAD

**Issue by alesl** [stacktracejs/stacktrace-gps#24]
Not sure if doing something wrong, but it appears SourceMap is cased as sourceMap. For this reason
https://github.com/stacktracejs/stacktrace-gps/blob/master/dist/stacktrace-gps.js#L108 fails for me.
As a workaround Im currently renaming sourceMap to SourceMap. Btw, Im doing this in browser.

**Comment by andreykl** [comment]
I think I has the same issue.

**Comment by eriwen** [comment]
Please let us know if this fix in https://github.com/stacktracejs/stacktrace-gps/commit/918d5d03aae44a1a6253d829ab24ce1fd2f83bf1 is sufficient.
