### ISSUE TITLE
sometimes the filename is <anonymous>

### ISSUE THREAD

**Issue by scamden** [stacktracejs/stacktrace-gps#32]
chrome sometimes evaluates JS in a VM and js that is evaled or crammed into a script tag manually will have filename anonymous. this results in an invalid network request for the source. would be best to just check for filename === '\<anonymous\>' and not do the fetches

**Comment by eriwen** [comment]
Huh... this seems like it could possibly be a parsing issue (`<anonymous>` is awful peculiar). It'd be awesome if you could provide a sample Error stack or code here.

**Comment by scamden** [comment]
I'll try to grab one, but it's not too crazy. The browser doesn't know the
file name if we xhr for a js blob and then manually eval it. It just knows
this is some anonymous piece of js. The weird part was when I was seeing
this for things executed for a frame in the vm. I'll try to provide an
example.
Sterling Camden

Sent from RelateIQ

On January 27, 2016 at 6:39 AMEric Wendelin<notifications@github.com> wrote:

Huh... this seems like it could possibly be a parsing issue (<anonymous> is
awful peculiar). It'd be awesome if you could provide a sample Error stack
or code here.

—
Reply to this email directly or view it on GitHub
<https://github.com/stacktracejs/stacktrace-gps/issues/32#issuecomment-175660378>
.
