### ISSUE TITLE
Cannot find sourceMappingURL, if the file has sourceURL instruction at the end.

### ISSUE THREAD

**Issue by evernikovskiy** [stacktracejs/stacktrace-gps#33]
The current pattern used to locate sourceMappingURL is:
/\/\/[#@] ?sourceMappingURL=([^\s'"]+)\s*$/

It assumes that the line with sourceMappingURL is the last line in the file.
However, some libraries (like RequireJS most likely) append additional information labeled sourceURL at the end of the file so in my case it looks like below (the top of the file has been truncated):

---

[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}ng\:form{display:block;}.ng-animate-shim{visibility:hidden;}.ng-anchor{position:absolute;}</style>');
//# sourceMappingURL=angular.min.js.map

//# sourceURL=http://localhost:63342/AppRoot/public/libs/js/angular.min.js

---

In this case the current RegEx pattern does not work. 

My temporary fix is to remove $ from the RegEx expression. It is not ideal but it works for me at this point. I hope that this issue will be addressed somehow in a future version.

**Comment by oliversalzburg** [comment]
This is how it's done in Chromium: https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/inspector/v8/V8StringUtil.cpp&sq=package:chromium&type=cs&l=16&rcl=1455164843
