### ISSUE TITLE
Usage example combining error-stack-parser and stacktrace-gps

### ISSUE THREAD

**Issue by jareware** [stacktracejs/stacktrace-gps#34]
Say I have the return value of `ErrorStackParser.parse()` and the related source map file, how do I combine those into a `gps.pinpoint(frames[1])` call without just getting a bunch of errors?

I assume I'd need to use `offline: true` in combination with `sourceCache: something`, but how? It looks like it's trying to fetch the original, minified source file as well. Is this actually even needed, if I have the stack frames and the source map?

Finally, `[ReferenceError: XMLHttpRequest is not defined]` tells me this may not have been designed to run on node. Would it be possible if `sourceCache` made HTTP requests unnecessary?

**Comment by eriwen** [comment]
Apologies for not addressing this sooner. I've added an example with https://github.com/stacktracejs/stacktrace-gps/commit/f0840f769571108a342bd31252051459279ffe46 — I hope this ends up being useful to you or others.

**Comment by jareware** [comment]
Thanks! I'll revisit this when I revisit the related part of our codebase. :)
