### ISSUE TITLE
Bluebird Promise Warnings

### ISSUE THREAD

**Issue by mlucool** [stacktracejs/stacktrace-gps#35]
Hi,

When I try this (via stacktrace.js) with webpack + bluebird promise I see the following warning:
"Warning: a promise was created in a handler but was not returned from it"

The warning seems to think its coming from:
https://github.com/stacktracejs/stacktrace-gps/blob/master/stacktrace-gps.js#L172
`StackTraceGPS:  this._get = function _get(location) {`

See: https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it

If this code is correct, can be it explicit so make bluebird not warn?

**Comment by mlucool** [comment]
Hi @eriwen any thoughts on this?

**Comment by eriwen** [comment]
This should be fixed by 8815f856785cfb0b85a8156aaaf80d4fc62f4b4c. Thanks @abhinavsinghvi!
