### ISSUE TITLE
Cannot find function names for ES6 static functions

### ISSUE THREAD

**Issue by rhart** [stacktracejs/stacktrace-gps#37]
## Expected Behavior

With a method that throws an error like:

```
static generate() {
    throw new Error('Boom');
}
```

the function name `generate` should be returned from `_findFunctionName`
## Current Behavior

Currently `undefined` is returned from `_findFunctionName` and a stack frame with an already populated function name from `error.stack` is replaced as 
`{anonymous}()@webpack:///src/main/lib/foo.js:15:10`
## Your Environment
- stacktrace.js version: 1.1.2
- Browser Name and version: Chrome 50.0.2661.94 (64-bit)
- Operating System and version (desktop or mobile): Yosemite

**Comment by eriwen** [comment]
Fixed with https://github.com/stacktracejs/stacktrace-gps/commit/c61d2b032dc34d81cb401bbb30f11afc1ced8929
