### ISSUE TITLE
dist folder not included when installing with bower

### ISSUE THREAD

**Issue by GustavSt** [stacktracejs/stacktrace-gps#39]
## Expected Behavior

When doing `bower install stacktrace-gps` the dist folder should be included, since the bower.json main property points to the js-file in the dist-folder
## Current Behavior

when doing `bower install stacktrace-gps` there is no dist-folder. There is no folder structure, everything is in the root folder
## Context

When using wiredep this package's main file is not automatically injected in my index.html. I'm using stacktrace-js that have this package as a dependency, and the other packages it has as dependency is correctly injected but not this one.
## Your Environment

- stacktrace.js version: 2.3.\* and 2.4.*
- Operating System and version (desktop or mobile): windows 10
- Bower version: 1.7.9
## Possible Solution

Set main to not be dist/{file}.js but just ./{file}.js. I'm not sure why dist folder is not included, could be the ignore of **_/_.\* ? If it is, maybe rethink that part so that dist-folder is included.

**Comment by eriwen** [comment]
Hmm. I'm not able to reproduce this. If I run `bower install stacktrace-gps` I get the `dist/` folder and everything under it. `**/.*` just excludes `.jscsrc` and other dotfiles. I'm trying this with stacktrace-gps 2.4.4.

Can you please confirm that you still don't see `dist/` with the latest stacktrace-gps?

**Comment by GustavSt** [comment]
Yeah, I seem to have gotten that error a while ago...
But when I try and install stacktrace-gps via bower I don't get a dist folder. If I install via npm I do get it.  For me it's the same with v 2.4.4 and 2.3.3.

**Comment by oliversalzburg** [comment]
Works fine for me.
