### ISSUE TITLE
Re-use mapConsumer when resolving multiple call stacks

### ISSUE THREAD

**Issue by mattzeunert** [stacktracejs/stacktrace-gps#41]
Every time `pinpoint` is called a new `SourceMap.SourceMapConsumer` object is created. Loading the source map into the consumer object is slow, so for multiple `pinpoint` calls the mapConsumer should be re-used.
## Possible Solution

This change could be made without any changes to the API. However, caching the mapConsumer uses a lot of memory, so maybe this behavior should be opt-in only.

Maybe a `cacheMapConsumers` boolean could be passed into the `StacktraceGPS` constructor?

I can submit a PR if we can agree on an API.

**Comment by abhinavsinghvi** [comment]
I was also facing similar problem, I have added https://github.com/stacktracejs/stacktrace-gps/pull/43. Let me know what do you think..

**Comment by eriwen** [comment]
This is partially fixed by https://github.com/stacktracejs/stacktrace-gps/commit/e173affba3ce0cf99838a02078c5e84b6732abd1 — we can take it a step further by splitting up `_extractLocationInfoFromSourceMapSource` and caching the Promise. This will prevent  creating multiple `SourceMapConsumers` when getting mapped location from the same source file (if multiple StackFrames reference the same source file).

I'm afraid I don't have time for this refactoring tonight. Hopefully will find time soon.

**Comment by eriwen** [comment]
@mattzeunert @abhinavsinghvi I created a candidate fix that caches SourceMapConsumer Promises, but as you can see it fails in a couple edge cases on Travis CI. I'm sure I missed something silly, but I'll have to attack this another day. It would be extra cool if one of you can figure out what I missed. Just run `gulp test-pr` to test in real browsers locally.

**Comment by mattzeunert** [comment]
I've reproduced and fixed the issue locally, and the PR is passing. But I think the PR tests are only a subset of the full tests from the push you referenced, so there might still be issues.

**Comment by eriwen** [comment]
This is fixed, as verified by tests, by merging #48. Thanks again both; this will ship in v3.0.0 soon!

**Comment by abhinavsinghvi** [comment]
What is the plan for releasing stacktrace js with these changes? Thanks.

**Comment by eriwen** [comment]
I'm hoping to prioritize some time on stacktrace.js in the next couple
weeks.

**Comment by abhinavsinghvi** [comment]
Hi Eriwen,

    Please let me know if you are planning to release stacktrace js library with these changes anytime soon.

Thanks,
Abhinav
