### ISSUE TITLE
sourceMappingURL regex matching earlier string instead of last line in webpack bundle

### ISSUE THREAD

**Issue by vjpr** [stacktracejs/stacktrace-gps#52]
I have many `//# sourceMappingURL` throughout my webpack bundle, but the important one is the last one.
  
*https://github.com/stacktracejs/stacktrace-gps/blob/master/stacktrace-gps.js#L129*:

```
 var m = /\/\/[#@] ?sourceMappingURL=([^\s'"]+)\s*$/m.exec(source);
```

It looks like the issue is the `/m` multi-line matcher. Removing this will correctly use the last match in the file. Otherwise it will use the first one.

You can try it in http://www.regexr.com

```
\/\/[#@] ?sourceMappingURL=([^\s'"]+)\s*$
```

```
//# sourceMappingURL=index.js.map

//# sourceMappingURL=main.bundle.js.map
```

Version 3.0.0.

**Comment by eriwen** [comment]
Fixed with #53 (also would've been fixed with #50) and released in v3.0.2.
