### ISSUE TITLE
Support inline source maps

### ISSUE THREAD

**Issue by eriwen** [stacktracejs/stacktrace-gps#7]
This library should consume inline source maps in addition to those in separate files.

**Comment by drkibitz** [comment]
I found this out trying out the new version of stacktrace-js. Being that the default behavior of browserify is to inline the source map, it would be very beneficial to support this imho.

**Comment by eriwen** [comment]
@drkibitz Totally agreed. I plan to get to it soon.

**Comment by niemyjski** [comment]
+1
