### ISSUE TITLE
Support cache merging

### ISSUE THREAD

**Issue by fresheneesz** [stacktracejs/stacktrace-gps#8]
I'm glad to see you're exposing the source cache, but its not enough to allow source caches to inter-operate. This has been really giving me issues in chrome lately, which seems to have some weird issue where it waits for a long time (like 20seconds) before it fulfills the second request for the same file (really odd - kind of the opposite of how caching is supposed to work).

But in any case, something is needed to allow other libraries to know if a request has been begun already, so they know to wait for that request to finish and use its result. The way I would do this is set values in the cache to the *promise* rather than the returned string. That way, the cache is filled immediately upon request, and other viewers of the cache can simply wait on that promise instead of making their own duplicate request.

I'd be willing to help make that change if you'd like.

**Comment by eriwen** [comment]
Sure, I'm willing to consider a PR for this.

**Comment by fresheneesz** [comment]
Thinking about it more, it might actually be better to allow the user to completely replace the ajax method. That way, if someone needed to store more information about the request than stacktrace.js needs, they can go ahead and store it in their own request cache and return a subset of the information that stacktrace.js needs when it calls it.

My use-case actually needs headers, so for a cached entry with contents but no headers I would either have to accept it and assume the headers won't be useful (which could break things in edge cases) or make another request.

Sorry to be flip flopping around, but the interface I'd suggest would actually be the ability to do something like:

```
stacktrace.setAjaxMethod(function(url) {
     //...
     // return requestBodyPromise
})
```

Thoughts?

**Comment by eriwen** [comment]
Hm.. I like the idea of allowing users to override behavior of underlying libraries. In this case, perhaps allowing users to supply a custom implementation of StackTraceGPS. like so:

```js
function MyGPS() {}
MyGPS.prototype = new StackTraceGPS();
MyGPS.prototype.ajax = function() { // custom implementation };
stacktrace.fromError({gps: MyGPS});
```

Tip of master now has a change to allow one using StackTraceGPS to override `ajax`. 

It'd be helpful to me if you could provide an example that demonstrates the "weird Chrome issue" as I have not been able to reproduce it myself.

**Comment by fresheneesz** [comment]
That's perfect. Thanks! When dyou think that'll be released in a tested version?

I packaged an example (not minimal) that demonstrates my problem and attached it to the bug I created for it here: https://code.google.com/p/chromium/issues/detail?id=458620&can=4&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

With some experimentation, I think its likely that the issue only appears when using synchronous ajax (I'm still using the old version of stacktrace.js). I won't know for sure until I finish updating my stuff with the new version tho.

**Comment by fresheneesz** [comment]
@eriwen I'm at the point where I need this to move forward with my usage of stacktrace.js. Currently, the way the sourcecaching mechanism works, and the behavior of how my use case asks for information, gps is ajaxing for the same file upwards of 80 times because the cache isn't populated until all those requests have already been made. 

Also, my tests are running way slower than they were before (now that i'm using the new version of stacktrace.js), and I don't think its the extra network requests. Previously my tests completed in about 3 seconds. Now they're taking 30-40s. Any idea why that would be?

**Comment by fresheneesz** [comment]
I manually changed _xdr and _get to populate the sourceCache with promises so that it doesn't make repeat requests, but I'm still seeing my test take over 30 seconds to complete - which again, is a 10X increase. Looking at the progression of the test, it seems to be stalling a lot - i'm not sure what its waiting for. 

Here's my code for _xdr and _get if you want to use it:

```
     function _xdr(url) {
        return new Promise(function (resolve, reject) {
            var req = _createXMLHTTPObject();
            req.open('get', url);
            req.onerror = reject
            req.onreadystatechange = function onreadystatechange() {
                if (req.readyState === 4) {
                    if (req.status >= 200 && req.status < 400) {
                        return resolve(req.responseText);
                    } else {
                        reject(new Error('Unable to retrieve ' + url));
                    }
                }
            };
            req.send();
        });
    }

        this._get = function _get(location) {
            return new Promise(function (resolve, reject) {
                if (this.sourceCache[location]) {
                    this.sourceCache[location].then(resolve).catch(reject)
                } else if (opts.offline) {
                    reject(new Error('Cannot make network requests in offline mode'));
                } else {
                    var result = this.sourceCache[location] = _xdr(location)
                    result.then(resolve).catch(reject)
                }
            }.bind(this));
        };
```

**Comment by fresheneesz** [comment]
I have a hypothesis for why my tests are running so much slower than they were with the old stacktrace.js. Deadunit (what i'm testing) not only has a source cache for the ajax responses, but it also keeps a cache of sourcemap consumers. I'm guessing those consumers take quite a bit of processing to generate, and since i'm asking for a stacktrace for things coming from somewhat large generated bundles hundreds of times, that can add up. What are your thoughts, @eriwen, on adding a cache for sourcemap consumers similar to the sourceCache?

**Comment by fresheneesz** [comment]
After more testing putting a cache for the sourcemap consumers, its still pretty much just as slow. I'm gonna have to give up for now. Its too slow for me to use at the moment and I have no idea where the slowness is coming from.

**Comment by fresheneesz** [comment]
Was this closed because swapping out a cache was implemented?
