### ISSUE TITLE
Downloading source

### ISSUE THREAD

**Issue by drkibitz** [stacktracejs/stacktrace-gps#9]
I' wondering why this is attempting to download all the sources, when it is embedded in the source map.
I first tried this lib, https://github.com/evanw/node-source-map-support which works fine in chrome, so I'm wondering can the same be done for safari, etc. with stacktrace.js?

**Comment by eriwen** [comment]
While the source map is sufficient for some cases, additional analysis on the original source can get us better results. 

I'm planning on adding this additional analysis later. See #5. 

If you think I ought to have an option *not* to download sources (just source maps) in stacktracejs/stacktrace.js, I'm willing to consider that.

**Comment by drkibitz** [comment]
@eriwen sorry for not getting back to you in a timely manner. It was decided that for the project I was proposing it for, stacktracejs was not the ideal tool for the job. Ultimately what I was looking for was a simple solution to transform stacktraces from uglified bundles back to source files, but not necessarily at runtime or even in the browser. I thought that if the source was included in the map, this would be enough. Though the need for downloading the source made this task significantly and maybe unnecessarily complex. I'd appreciate in more opinions on this if you have any, if not that's fine too ;)
